Acme\DemoBundle\Entity\Mobile:
    properties:
        name:
            - Length:
                min: 2
                max: 50
                minMessage: "Your first name must be at least {{ limit }} characters long"
                maxMessage: "Your first name cannot be longer than {{ limit }} characters long"
